[package]
name = "udata-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cef = { path = "vendor/cef-rs/cef" }
uuid = { version = "1.16.0" , features = ["v4"] }
base64 = "0.22.1"
pretty-hex = "0.4.1"
serde = "1.0.219"
serde_json = "1.0.140"